### ISSUE TITLE
CORS error and wrong domain when importing from Experimenter Stage

### ISSUE THREAD

**Issue by mythmon** [mozilla-extensions/normandy-devtools#111]
While testing #107, I tried to import a recipe from Experimenter. The add-on URL, but none of the data loaded, and the console contains these errors:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://experimenter.services.mozilla.com/api/v1/experiments/multiple-addon-rollout-412020/recipe. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://experimenter.services.mozilla.com/api/v1/experiments/multiple-addon-rollout-412020/recipe. (Reason: CORS request did not succeed).

> TypeError: NetworkError when attempting to fetch resource.

This is the experimenter ticket I tried to import: https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/multiple-addon-rollout-412020/

The resulting add-on URL was ext+normandy://stage/recipes/import/multiple-addon-rollout-412020

**Comment by rehandalal** [comment]
I tried a "no-cors" request but because of the Auth0 implementation on Experimenter that doesn't work. I think there are a few solutions to this but they all involve changes to Experimenter so I tagged @jaredlockhart in.
