### ISSUE TITLE
How can I use Normandy Dev Tools with my local dev instance of Experimenter?

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla-extensions/normandy-devtools#158]
It'd be nice to have some way to use a Normandy Dev Tools build that I can use with my local dev experimenter, and especially that talks to my local dev instance of Normandy.

**Comment by rehandalal** [comment]
This already exists?? If you grab the latest release from the releases page you should be able to switch to "Local":

Click on this button in the header:
<img width="193" alt="image" src="https://user-images.githubusercontent.com/987136/80894430-e3a72d80-8ca8-11ea-9be1-81770bb4305b.png">

Then choose "Local" from the dropdown:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/987136/80894445-f9b4ee00-8ca8-11ea-9233-0d88c14a4930.png">

You should now be speaking to your local dev instances. Unless you have them configured in a non-standard way (i.e. not on `https://localhost:8000/` for Normandy and `https://localhost/` for Experimenter). In that case you will need to create your own build with those configured for your system and run a development build until we add UI for configuring the Local instances which is what I was going to tweak issue #44 to cover.

**Comment by mythmon** [comment]
It seems like the question here was answered. @jaredlockhart, feel free to re-open if you needed more help here.
