### ISSUE TITLE
Always set `isEnrollmentPaused`

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla-extensions/normandy-devtools#190]
We recently saw that if `isEnrollmentPaused` is missing entirely from a recipe, Experimenter misinterpreted it: https://github.com/mozilla/experimenter/issues/2660

We can update Experimenter to handle the case that it's missing, but we should probably also make sure that field is required and always set.  I think changing it on the Normandy Server side to make it required and have a default is a more involved change, but Normandy Dev Tools should be able to make sure it's always passed in?

**Comment by b4handjr** [comment]
Hey, I'd like to work on this. Can I get an idea of what I would need to do?

**Comment by tiftran** [comment]
Hi @jrbenny35,

Dev set up instructions are here if you haven't already found them https://mozilla-extensions.github.io/normandy-devtools/#/dev

**Comment by b4handjr** [comment]
@tiftran I have setup my environment. Where should I start?

**Comment by tiftran** [comment]
So [this](https://github.com/mozilla-extensions/normandy-devtools/blob/master/extension/content/components/pages/RecipeFormPage.js#L32-L43) is where NDT calls the experimenter api to retrieve recipe data....
This would probably be where you would start poking at
Depending on the action of the isEnrollmentPaused should be included.

**Comment by b4handjr** [comment]
If I wanted to test a change I made to that code, how could I do that? @tiftran

**Comment by tiftran** [comment]
- Have a local experimenter and local NDT
- Open up experimenter in the same browser as your local NDT
- Create an add on experiment in Experimenter
- Progress through the process until the "Ready to Ship" state
- You should then see a blue "Send to Normandy" button
- Clicking on the button should open a new NDT tab
- Experimenter info should be imported into NDT
- Clear the import instructions field
- Fill in any required fields that are needed
- Without touching the enrolment toggle save the recipe
- The new recipe should be listed in NDT now
- Click the "view recipe" button for the new recipe
- Enrollment Paused? should display no

**Comment by mythmon** [comment]
I think that this was done in #281 and #254.
