### ISSUE TITLE
Logo SVG makes many tests hard to debug

### ISSUE THREAD

**Issue by mythmon** [mozilla-extensions/normandy-devtools#424]
Often while debugging test output, the testing framework tries to print the document in which it could not find the expected element. Most tests render the entire document (so it doesn't have to mock state as much), which means that the document includes the SVG logo, which is lengthy.

![image](https://user-images.githubusercontent.com/305049/93258725-9c02d900-f753-11ea-889f-6e5da749b639.png)

The SVG content extends a long ways and eventually the test framework just cuts it off, usually hiding the place where the bug actually is. This makes testing more difficult than it should be.

**Comment by mythmon** [comment]
My personal workaround is to temporarily edit `Logo.tsx` to remove that path.

**Comment by leplatrem** [comment]
The fact that warnings are shown in red also doesn't help...
