### ISSUE TITLE
Recipe listing page

### ISSUE THREAD

**Issue by rehandalal** [mozilla-extensions/normandy-devtools#45]
I would like to take a different approach from Delivery Console for the listing page:
- Recipes are only shown one action type at a time
- Recipes are shown as cards instead of tabular data
- The cards are customized by the type of action
- A generic card design will be required for new actions (or actions that don't require custom UI)
- There should be a indicator on all cards that displays whether a recipe has already been executed
- There should be a search field to filter down recipes

**Comment by mythmon** [comment]
With #362 done, I think we have enough here to call this finished. What we built isn't exactly what Rehan laid out in the original issue description, but I think we've got to a good place.
