### ISSUE TITLE
Can't save a recipe if you connect to the VPN after opening the NDT page

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-extensions/normandy-devtools#523]
**[Affected versions]:**
- Firefox Nightly 83.0a1, Build ID 20201014214248

**[Affected Platforms]:**
- Windows 10

**[Prerequisites]:**
- Have VPN access to the staging environment.
- Have the NDT addon (version 2.1.1) installed on a new profile.
- Have the VPN disabled.

**[Steps to reproduce]:**
1. Open the Firefox profile from prerequisites and click the NDT button from the Browser Toolbar.
2. Switch to the `Stage` environment and click the `Create Recipe` button.
3. Fill the fields with valid values.
4. Connect to the VPN and click the `Save` button.
5. Leave a comment and click the `Save` button again.
6. Observe the behavior.

**[Expected results]:**
- The recipe is successfully saved.

**[Actual results]:**
- `An Error Occurred: {"status":403}` is displayed.

**[Notes]:**
- The issue is NOT reproducible when editing a recipe in stead of creating one.

**Comment by mythmon** [comment]
This is a workflow that I use quite often. Sometimes it takes a moment for NDT to detect the VPN change and switch over to the other server. Can you verify that the Environment selector in the top right has a green dot on it while you are seeing this error?

If that doesn't help, can you provide the logs from the Firefox Devtools console, and also the network activity as a HAR file from the network panel?

**Comment by SoftVision-CiprianMuresan** [comment]
I redid the steps and it looks like the issue was with me trying to save a recipe right after connecting to the VPN. If I wait ~15s it works as expected. 
The green dot however is not present in the environment selector and does not appear after switching environments. It does appear if I open a new NDT tab.

Given this, I'll close the issue.
