### ISSUE TITLE
The line number is overlapping the string in the “Extra Filter Expression” field if the recipe was sent to Normandy from the Experimenter page

### ISSUE THREAD

**Issue by Martin-Robert** [mozilla-extensions/normandy-devtools#594]
**[Affected Versions]:**
- Firefox Release 82.0.2 (Build ID: 20201027185343)
- Firefox Beta 83.0b8 (Build ID: 20201103183834)
- Firefox Nightly 84.0a1(Build ID: 20201105045247)
- Normandy DevTools v2.2.0
- Normandy DevTools v2.1.1

**[Affected Platforms]:**
- Windows 10 x64

**[Prerequisites]:**
- Have a profile that can be targeted by Normandy stage recipes.
	- For more info: [Normandy prerequisites](https://docs.google.com/document/d/13yxuvfpIGojY1FSsUJYHKUUQldKkSW0UzrUirdC0kQ0/edit#bookmark=id.k2nk5lj7jzh1).
- Have VPN access to the staging environment.
- Have the v2.2.0 [Normandy Devtools](https://github.com/mozilla-extensions/normandy-devtools/releases/tag/v2.2.0) add-on installed.
- Have an [Experimenter ticket](https://stage.experimenter.nonprod.dataops.mozgcp.net/) in the “Ready to Ship” state.

**[Steps to reproduce]:**

Start the Firefox profile from prerequisites.
Navigate to the Experimenter page.
Open the “Ready to Ship” experiment.
Click the “Send to Normandy” blue button.
Focus the “Extra Filter Expression” text field.
Write a string and observe the text field.

**[Expected results]:**
- The string is correctly displayed.
    
**[Actual results]:**
- The string is overlapped by the line number.

**[Notes]:**
- The issue is not reproducible if the recipe is manually created using the NDT add-on.
- The issue is reproducible for the “Additional Filter Objects” text field.
- The issue is reproducible on older NDT add-on versions.
- Attached a screen recording of the issue.

![2020-11-05_14h57_56](https://user-images.githubusercontent.com/55738964/98249670-324ac280-1f7f-11eb-9d0d-0188601a1059.gif)

**Comment by mythmon** [comment]
I poked at this a bit, and what I noticed is that *sometimes* the line numbers show up just fine, but it's rare. It's not a inconsistency in our build system, and I can't make it reproduce reliably. It seems rare. When it does happen, the dom is different, with some elements missing content and inline styles. I'm not sure where to go from here though.

**Comment by Softvision-PatriciuPop** [comment]
I have verified that the issue is no longer reproducible using the following [build](https://github.com/mozilla-extensions/normandy-devtools/runs/1659305385). Tested using Firefox Nightly 86.0a1, Build ID 20210111215143 on Windows 10 x64.
