### ISSUE TITLE
normandy.os is undefined on Beta 62

### ISSUE THREAD

**Issue by eqrion** [mozilla-extensions/normandy-devtools#6]
Not sure if this is the best place to file this, feel free to move.

When testing out the recipe for the P-OMTP study, I noticed that `normandy.os` was always undefined on my Windows computer in Firefox Beta 62.

Switching to Nightly 63, `normandy.os` has the correct value.

This is on the same machine. I've confirmed it on a different Windows computer as well. I have not tested other platforms.

<img width="1280" alt="beta-62" src="https://user-images.githubusercontent.com/4984292/43424575-8595efca-9415-11e8-8e28-437ed012d535.PNG">

<img width="1280" alt="nightly-63" src="https://user-images.githubusercontent.com/4984292/43424577-876bc4c8-9415-11e8-869b-1f6f2d0058be.png">

**Comment by mythmon** [comment]
This is expected, since the `normandy.os` context variable landed in [Nightly 63](https://bugzilla.mozilla.org/show_bug.cgi?id=1472797). This means the P-OMTP study recipe will need some tweaks though. We can get OS info from telemetry. I'll follow up with S&I.
