### ISSUE TITLE
The syntax from the “Additional Filter Objects” section is removed after saving the recipe, if it is related to the recipe sections

### ISSUE THREAD

**Issue by SoftVision-SimonaRosu** [mozilla-extensions/normandy-devtools#621]
[Affected versions]:
 - Firefox Release 83.0 (Build ID: 20201112153044)

[Affected Platforms]:
 - Windows 10 x64

[Prerequisites]:
- Have the Firefox browser installed.
- Have the [Normandy Devtools V2.2.0](https://github.com/mozilla-extensions/normandy-devtools/releases) addon installed.
- Have VPN access to the staging environment.

[Steps to reproduce]:
1. Open the Normandy Devtools and choose the Stage environment.
2. Set up any experiment recipe ([link to set-up](https://docs.google.com/document/d/1_vE5L8qZzvHTB9VVtdhrKuoxuxCvwOxvcRBTRFDGoSw/edit))  targeting your browser using an additional filter object related to the recipe sections. 
e.g.:
 [
  {
    "type": "locale",
    "locales": ["en-US"]
  }
]
3. Click on the “Save” button.
4. Click on the “Edit” button.
5. Observe the “Additional Filter Objects” section.

[Expected result]:
 - The syntax is displayed in the “Additional Filter Objects” section.

[Actual result]:
 - The syntax is no longer displayed.

[Notes]:
- Attached a screen recording of the issue.

![AdditionalFilter_removed](https://user-images.githubusercontent.com/50919288/99554876-5b7c4180-29c8-11eb-8f5d-e7768ca7d27e.gif)

**Comment by mythmon** [comment]
Normandy server uses canonical JSON, which removes all formatting. NDT adds nice formatting to the data. It is not expected to maintain the formatting of JSON data.

**Comment by mythmon** [comment]
Filters that have UIs are not shown in extra filter objects. It is not a separate field. This is working as expected.
