### ISSUE TITLE
Action selector re-requests actions on every key press in create recipe page

### ISSUE THREAD

**Issue by mythmon** [mozilla-extensions/normandy-devtools#683]
On the recipe creation page, typing in any of the text boxes (like the extra filter expression), causes the action selector to re-fetch the list of actions from the server on every key press. That's bad.

![image](https://user-images.githubusercontent.com/305049/107268525-1bdc5900-69fd-11eb-92e3-65df3e617254.png)

**Comment by rehandalal** [comment]
😲
