### ISSUE TITLE
Decide list of Shield Study Addon developer tools to facilitate QA and local dev of studies.

### ISSUE THREAD

**Issue by gregglind** [mozilla-extensions/normandy-devtools#7]
Things that would be cool for testing shield studies addons (incomplete list)

- record all telemetry the addon sent
- show that setActiveExperiment worked
- simulate endings
- choose a branch, in a way that the addon / utils can see it?   (pref suggested, but other things are better).  
- reinstall addon with new cleared conditions.

**Comment by mythmon** [comment]
This is from a different time, and not really relevant to today's work.
