### ISSUE TITLE
We are not able to successfully connect to Normandy stage environment and create/edit/disable recipes

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-extensions/normandy-devtools#749]
**[Affected Versions]:**
- Firefox Nightly 97.0a1
- Firefox Beta 96.0b5 
- Firefox Release 95.0

**[Affected Platforms]:**
- Windows 10 x64
- macOS 10.15.7
- Ubuntu 20.04 x64

**[Prerequisites]**
- Have access to Normandy stage environment.
- Have LDAP accounts.
- Be connected to OpenVPN with a valid account.

**[Steps to reproduce]:**
1. Open the Firefox build and install the [Normandy Dev Tools](https://github.com/mozilla-extensions/normandy-devtools/releases/tag/v2.3.1) addon.
2. Click the Normandy Dev Tools button from the browser toolbar.
3. Login with LDAP account. 
4. Switch to the "Stage" environment.
5. Click on an enabled recipe and try to disable it.
6. Observe the behavior.

**[Expected results]:**
- The recipe is successfully disabled.
    
**[Actual results]:**
- A "An Error Occurred: "JSON.parse: unexpected character at line 2 column 1 of the JSON data"" error is displayed and the recipe cannot be disabled.

**[Notes]:**
- Usually, we have a green dot displayed on the avatar when we are successfully connected to the Normandy stage environment, but now the greed not is no longer displayed.  
- Attached is a screen recording of the issue.
![Normandy stage enivroment](https://user-images.githubusercontent.com/19226534/145982945-39e1452d-ee04-4514-a1de-69fa5343a838.gif)

**Comment by mythmon** [comment]
NDT isn't connected to the admin servers. When it is, the environment selector has a small green dot on it. This could be caused by not being connected to the VPN, you not having the correct VPN permissions, or simply by NDT not having picked up the connection yet. There may be additional details in the console or network tabs of the browser devtools.

**Comment by SoftVision-CosminMuntean** [comment]
@mythmon thanks for looking over this. I was connected to the VPN and also my colleagues tried this, but we don't have the green dot on the Stage environment and we cannot edit/disable recipes. Also, @SoftVision-CiprianMuresan has access to the Production server and he has the green dot on it, but he didn't have it on the Stage environment. 
We should have the correct permissions on the Stage environment since we were able to create/edit/disable recipes about a week ago, unless if the permissions were currently changed. 

Here are the logs from the Network tab: [link](https://drive.google.com/file/d/14RDtAP7WGbMhwvFVVMyQJmt4POTQqfEY/view?usp=sharing). Please let me know if you need any other information.

**Comment by smarnach** [comment]
@SoftVision-CosminMuntean Could you please try again? It's possible this is fixed now, though I'm not completely sure.

**Comment by mythmon** [comment]
I tested this using the same technique Cosmin was, and it seems to be working for me now.

**Comment by SoftVision-CosminMuntean** [comment]
@smarnach @mythmon Thank you for looking over the issue. We just verify and we are successfully connected to the Normandy stage environment and we can create/edit/disable recipes. Considering this, I will mark this issue as verified fixed.
