### ISSUE TITLE
Unable to successfully connect to the Normandy Stage environment and create/edit/disable recipes

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla-extensions/normandy-devtools#753]
[Affected Versions]:

- Firefox Nightly 98.0a1
- Firefox Beta 97.0b4
- Firefox Release 96.0.1

[Affected Platforms]:

- Windows 10 x64
- macOS 11.6.2
- Ubuntu 20.04 x64

[Prerequisites]

- Have access to Normandy stage environment.
- Have a valid LDAP account.
- Be connected to OpenVPN with a valid account.

[Steps to reproduce]:

1. Open the Firefox build and install the Normandy Dev Tools addon.
2. Click the Normandy Dev Tools button from the browser toolbar.
3. Login with an LDAP account.
4. Switch to the "Stage" environment.
5. Click on an enabled recipe and try to disable it.
6. Observe the behavior.

[Expected results]:

- The recipe is successfully disabled.

[Actual results]:

- The "An Error Occurred: "JSON.parse: unexpected character at line 2 column 1 of the JSON data"" error is displayed and the recipe cannot be disabled.

[Notes]:
- Usually, we have a green dot displayed on the avatar when we are successfully connected to the Normandy stage environment, but now the greed not is no longer displayed.
- This is the same issue described in https://github.com/mozilla-extensions/normandy-devtools/issues/749

**Comment by smarnach** [comment]
I rolled back a Remote Setting release we did last week, which may be related (though I couldn't really see evidence for it this time). Could you please try again?

**Comment by Softvision-PatriciuPop** [comment]
I have just verified this and I can successfully connect to the Normandy stage environment and edit recipes. Considering this, I will mark this issue as verified fixed. Thank you for looking over this.
